version: "3"
services:
  web:
    build: ./web
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_APP: ./app.py
      FLASK_DEBUG: 1
    ports: ['5000:5000']
    volumes: ['./web:/app']
    links:
      - db
    depends_on:
      - db
  db:
    build: ./db
